default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        exclude_types:
          - "yaml"

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [json]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.267"
    hooks:
      - id: ruff
        args:
          - --fix
